### ISSUE TITLE
iPhone 5 (and assuming earlier) don't display wallpaper or icons.

### ISSUE THREAD

**Issue by CommanderNeon10** [soupy-developer/auroraOS#10]
**Describe the bug**

No icons or wallpaper on my daily-driven iPhone 5.

**To Reproduce**
Steps to reproduce the bug. Only needed in some cases.

Take an old iPhone 5, and try to run the website.

**Expected behavior**
A clear and concise description of what you expected to happen instead.

Regular auroraOS.

**Screenshots**
Screenshots showing the bug. Only needed in some cases.

![IMG_2827](https://user-images.githubusercontent.com/58310402/80756271-342f5700-8b00-11ea-8270-77406dd4ba06.PNG)

**Browser**
Browser info, e.g. user agent, browser and version, or anything else that helps us identify your browser.
Try listing any flags or experiments you have enabled, if applicable.
Example: Google Chrome Canary 69.420

iOS 10.3.4 on an iPhone 5

**Comment by eitan3085** [comment]
Safari does not support WebP images. We'll try to add PNG fallbacks soon.

**Comment by CommanderNeon10** [comment]
ok
