### ISSUE TITLE
"Industrial Dark" theme makes taskbar disappear

### ISSUE THREAD

**Issue by onyxcode** [soupy-developer/auroraOS#3]
Although apps, the start button and time/date still show, the background of the taskbar becomes invisible.
![Screenshot](https://user-images.githubusercontent.com/58049576/73195904-aa38b200-40fc-11ea-8963-ffeceb5bb1fa.png)

**Comment by CommanderNeon10** [comment]
I'm thinking this design was on purpose. However I don't like this design either.

**Comment by soupy-developer** [comment]
That design was on purpose with both Industrial themes.

**Comment by eitan3085** [comment]
Fixed in 4.5
