### ISSUE TITLE
Migrate away from Glitch

### ISSUE THREAD

**Issue by onyxcode** [soupy-developer/auroraOS#4]
Although Glitch has great hosting, it shuts down the server if there are no active users. My advice is you are better off finding a free domain on [Freenom](https://freenom.com) and hosting auroraOS on [GitHub Pages](https://github.io) or [Zeit](https://zeit.co).

**Comment by soupy-developer** [comment]
auroraOS cannot be hosted on Github Pages or Zeit due to the fact that it requires a custom Node.js backend. GitHub only serves static files and I assume the same with Zeit.

**Comment by onyxcode** [comment]
@soupy-developer If you want a custom Node.js backend, check out [Netlify](https://netlify.com), I'm almost positive that will work for you, and it doesn't shut down. Did I mention it's ***free?***
