### ISSUE TITLE
Laggy window movement when using touch

### ISSUE THREAD

**Issue by CommanderNeon10** [soupy-developer/auroraOS#9]
**Describe the bug**

When using touch, dragging windows is very laggy. Should start off smooth, then become very VERY choppy.

**To Reproduce**
Steps to reproduce the bug. Only needed in some cases.

Use a touch device and drag a window around.

**Expected behavior**
A clear and concise description of what you expected to happen instead.

The window to drag smoothly.

**Screenshots**
Screenshots showing the bug. Only needed in some cases.

n/a

**Browser**
Browser info, e.g. user agent, browser and version, or anything else that helps us identify your browser.
Try listing any flags or experiments you have enabled, if applicable.
Example: Google Chrome Canary 69.420

Google Chrome on Google Chrome OS Stable 81.4044.94

**Comment by eitan3085** [comment]
Possible fix applied, the culprit was pull-to-refresh.
Let us know if this is still occuring.
